### ISSUE TITLE
it does not worked on Ubuntu 22.04

### ISSUE THREAD

**Issue by dtantono** [Samueru-sama/Ryujinx-AppImage#1]
I downloaded the Appimage and it shows me this error
<img width="809" alt="image" src="https://github.com/Samueru-sama/Ryujinx-AppImage/assets/29157187/e21ff8b0-462c-4d9b-8507-7f991cc44617">

**Comment by Samueru-sama** [comment]
> I downloaded the Appimage and it shows me this error <img alt="image" width="809" src="https://private-user-images.githubusercontent.com/29157187/320710532-e21ff8b0-462c-4d9b-8507-7f991cc44617.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzQwODMsIm5iZiI6MTcxMjYzMzc4MywicGF0aCI6Ii8yOTE1NzE4Ny8zMjA3MTA1MzItZTIxZmY4YjAtNDYyYy00ZDliLTg1MDctN2Y5OTFjYzQ0NjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAzMzYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MmU1OGEzYzQ4Yjk0MTE2YTYxMzExZTZkYmY3MzE0NjMwNWJlYzJjMmZmZTkwNmNlOTMwNTJjNjNkOWY2NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H6PaO3yZDQ7tVLDdLnUjHBMcslmJtti11Fbuc6-8dZ0">

Can you do a `./Ryujinx-177-x86_64.AppImage --appimage-extract && cd ./squashfs-root && ./AppRun"? This way we can know that at least Ryu isn't broken. 

Do you have appimagelauncher installed?

**Comment by Samueru-sama** [comment]
> Yes, I have an appimagelauncher. But for this first run, I just run it once. and when I tried to give a permission. I got this error <img alt="image" width="674" src="https://private-user-images.githubusercontent.com/29157187/320715563-ba4f09ef-dadb-4e14-abb9-f9cfac4949e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzQ4OTksIm5iZiI6MTcxMjYzNDU5OSwicGF0aCI6Ii8yOTE1NzE4Ny8zMjA3MTU1NjMtYmE0ZjA5ZWYtZGFkYi00ZTE0LWFiYjktZjljZmFjNDk0OWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAzNDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMjQ3MTNjYWMyOTgyMjAyODRhYmJjMmY3OTY0MmQ2NzY4ODliY2JlNGMxNDUzMWFhZDRjYmM3MzY3MWZlOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uc0kiuMrTOAenbP2vd59VDUFKzCIDJGABHn6ocLeFr8">

This is likely an issue with appimage launcher, I tried to use it with the official releases of yuzu and cemu and it failed. 

You can test removing appimagelauncher and rebooting your pc and try to launch the appimage again. Let me know if it launches once you do that.

Also I just learned that someone was already doing ryu appimages lol: https://github.com/qurious-pixel/Ryujinx/releases/tag/continuous

**Comment by dtantono** [comment]
tbh, that https://github.com/qurious-pixel/Ryujinx/releases/tag/continuous is working properly than your build.

**Comment by Samueru-sama** [comment]
> tbh, that https://github.com/qurious-pixel/Ryujinx/releases/tag/continuous is working properly than your build.

Ok but please try launching it without appimagelauncher to see if mine works.

**Comment by Samueru-sama** [comment]
> tbh, that https://github.com/qurious-pixel/Ryujinx/releases/tag/continuous is working properly than your build.

I just installed appimagelauncher on my system and indeed, now I have the problem on my end: 

![image](https://github.com/Samueru-sama/Ryujinx-AppImage/assets/36420837/b44b3534-3b08-4942-8cce-f658e253a6b8)

Be aware that appimagelauncher is essentially dead at this point, its last release was like 3 years ago. If you want an alternative look at AM from Ivan-hc. 

I'll be closing the issue, if you still have the issue even without appimagelauncher installed let me know and I'll gladly help.
