### ISSUE TITLE
 1.1.1403 AppImage

### ISSUE THREAD

**Issue by mikae1** [Samueru-sama/Ryujinx-AppImage#2]
Could be useful to have an AppImage build of the last Ryujinx version (1.1.1403) now that their repo is gone... Seems to be [a mirror here](https://git.naxdy.org/Mirror/Ryujinx/).

**Comment by Samueru-sama** [comment]
Hello, this repo used the portable build of Ryujinx to build the AppImage, I don't see any releases in that mirror.

Unfortunately I setup the CI to build automatically every 2 days and today it was going to run but [it failed 4 hours ago](https://github.com/Samueru-sama/Ryujinx-AppImage/actions/runs/11129308097) which seems it was very close to the time the repo went down.

**Comment by mikae1** [comment]
> Unfortunately I setup the CI to build automatically every 2 days and today it was going to run but [it failed 4 hours ago](https://github.com/Samueru-sama/Ryujinx-AppImage/actions/runs/11129308097) which seems it was very close to the time the repo went down.

Ouch, sometimes the timing just ain't right. Thanks anyways!

**Comment by Innarel** [comment]
You saved the community. Hope this appimage works for a long time. Flatpak version will soon be gone.

**Comment by Mervius** [comment]
if we know how the portable versions were created from the source, there could be a two-step process.

**Comment by getBoolean** [comment]
You can still access the latest commit at https://github.com/emmauss/Ryujinx/tree/a2c003501371463fd1f98d2e5a7602ae19c21d7c

**Comment by Samueru-sama** [comment]
> You can still access the latest commit at https://github.com/emmauss/Ryujinx/tree/a2c003501371463fd1f98d2e5a7602ae19c21d7c

Sorry but I don't see any links to the portable build there. 

Ryujinx never got to release an official AppImage, they instead had a portable tar.gz build for linux, all this repo did was turn that into an AppImage, there was no compiling being done here.

Also the releases to the portable build were on a different repo of Ryujinx called [release-channel-master](https://github.com/Ryujinx/release-channel-master).

With that said Suyu has a [mirror of that repo](https://git.suyu.dev/ryujinx-backup/release-channel-master), if they get the CI up and running I can switch this repo to use that.

**Comment by getBoolean** [comment]
Thanks for sharing that release channel repo, didn't realize repo was being used. I was able to get CI working on my fork, though with the version number hard coded

**Comment by Samueru-sama** [comment]
> Thanks for sharing that release channel repo, didn't realize that repo was being used. I was able to get CI working on my fork, though with the version number hard coded

Thank you, I also made a separate release using your mirror and also kept that last release from the Ryujinx repo saved.

**Comment by getBoolean** [comment]
Awesome. Let's hope this will only be a temporary change and a new fork maintainer volunteers.

**Comment by mikae1** [comment]
> Thank you, I also made a separate release using your mirror and also kept that last release from the Ryujinx repo saved.

You're officially awesome. Thanks!

**Comment by Samueru-sama** [comment]
Update, there is now this hard-fork of ryujinx, and I helped the maintainer to [make official appimage](https://github.com/ryujinx-mirror/ryujinx/releases/tag/r.dc545c3) releases.

This repo will now be archived.

I remember back on the original Ryujinx repo the issue for an appimage was open for years and at some point after yuzu was taken down someone commented how important to was to make appimage releases just in case the same happened to Ryujinx and well now here we are but at last now there are easily accessible appimage builds (also for aarch64) in the hard-fork.
