### ISSUE TITLE
How to add to Emudeck?

### ISSUE THREAD

**Issue by DEMAK1337** [Samueru-sama/Ryujinx-AppImage#3]
Hi just a question on how to add the files to emudeck if anyone knows?
ive moved  the appimage to /home/deck/Applications but no luck in configuring it with emudeck.

**Comment by Samueru-sama** [comment]
I'm not an emudeck user so I really don't know. However iirc in order to use suyu you had to rename the appimage to yuzu in emudeck, that makes me think that emudeck does not support the Ryujinx appimage at all since they never had an official one.

**Comment by Samueru-sama** [comment]
The [hard fork of Ryujinx](https://github.com/ryujinx-mirror/ryujinx/releases/tag/r.cfa287f) now has AppImage builds, you might wanna tell the emudeck folks to switch to using that repo by default.
