### ISSUE TITLE
Make it so that the .sh file builds from the ryujinx-mirror Hard Fork of Ryujinx.

### ISSUE THREAD

**Issue by Mahim2000** [Samueru-sama/Ryujinx-AppImage#4]
Also if possible, let the newer AppImages be based on any new builds of that aforementioned Mirror

https://github.com/ryujinx-mirror/ryujinx

**Comment by Samueru-sama** [comment]
> Also if possible, let the newer AppImages be based on any new builds of that aforementioned Mirror
> 
> https://github.com/ryujinx-mirror/ryujinx

Hello, I already made a [PR](https://github.com/ryujinx-mirror/ryujinx/pull/28) there so that you can get the AppImage builds directly from that repo. I don't see an urgent need to switch this repo to start building from there but will see.

**Comment by Samueru-sama** [comment]
The PR has been merged and now the repo has zsync releases.
